# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-13 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_auto_20190713_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name_plural': '菜单'},
        ),
    ]
